application: feedgenerator
version: 6
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?.*/CVS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$

handlers:
- url: /sourcecodeonline/scraper
  script: sourcecodeonline/scraper.py
  login: admin

- url: /sourcecodeonline/?
  script: sourcecodeonline/rss.py
  
- url: /filetransit/scraper
  script: filetransit/scraper.py
  login: admin

- url: /filetransit/?
  script: filetransit/rss.py
  
- url: /filehungry/scraper
  script: filehungry/scraper.py
  login: admin

- url: /filehungry/?
  script: filehungry/rss.py   
  
- url: /vclcomponents/scraper
  script: vclcomponents/scraper.py
  login: admin

- url: /vclcomponents/?
  script: vclcomponents/rss.py
  
- url: /componentsource/scraper
  script: componentsource/scraper.py
  login: admin

- url: /componentsource/?
  script: componentsource/rss.py
  
- url: /
  static_files: index.html
  upload: index.html
  
- url: /
  static_files: sitemap.xml
  upload: sitemap.xml
  
- url: /img/(.*)
  static_files: img/\1
  upload: img/(.*)   
 